#include <stdio.h>
#include <stdlib.h>
#include "memSimFuncs.h"

struct memory {
  int refCount;
  char *commands;
};

//  Generates a new dynamic array and assigns each field to their default values
MEMORY *newMEMORY(int refCount) {
    MEMORY *m = malloc(sizeof(MEMORY));
    m->refCount = refCount;
    m->commands = malloc(sizeof(char *) * refCount);
    return m;
}

void setCommand(MEMORY *m, char command, int index) {
  m->commands[index] = command;
  return;
}

MEMORY *readFile(FILE *fp) {
  int count = 0, address = 0;
  char command;

  fscanf(fp, "%d", &count); // Get the number of memory references
  MEMORY *m = newMEMORY(count);
  for (int i = 0; i < count; i++) {
    // Get Command
    fscanf(fp, "%c", &command);
    while (command != 'R' && command != 'W') {
      fscanf(fp, "%c", &command);
    }
    // Get Address
    fscanf(fp, "%d", &address);
  }
  return NULL;
}


char getAssociativity() {
  char degree = '\0';
  printf("Enter the degree of set-associativity (input n for an n-way set-associative mapping) : ");
  scanf("%c", &degree);
  while ((getchar()) != '\n');
  return degree;
}

char getReplacementPolicy() {
  char policy = '\0';
  printf("Enter the replacement policy : ");
  scanf("%c", &policy);
  while ((getchar()) != '\n');
  return policy;
}

FILE * getFile() {
  FILE *fp = NULL;
  char filename[20];
  printf("Enter the name of the input file containing the list of memory references generated by the CPU : ");
  scanf("%s", filename);
  fp = fopen(filename, "r");
  return fp;
}
